### ISSUE TITLE
feat: 소상공인 정보를 담은 게시판을 구현한다.

### ISSUE THREAD

**Issue by 2yunseong** [jnu-resellers/resellers-fe#78]
- 소상공인 진흥 사업단 링크를 모아둔 페이지를 구현한다.
- 자료를 리서치하고, 게시판 형태로 만든다.
- 멘토링일지 참고 바람

**Comment by dxwwan** [comment]
오늘 자료조사 후, 월요일에 민준님과 하루만에 끝내버리겠습니다!
